/* -------------------------------------------- Magnet Gaming Party Server -------------------------------------------- */

/* ----------------------------------------------------- Defines ------------------------------------------------------ */

/* General */
#define scriptVersion "v0.0.1"
/*---------*/

/* Colours */
#define COLOUR_GREY 0xAFAFAFAA
#define COLOUR_GREEN 0x33AA33AA
#define COLOUR_RED 0xAA3333AA
#define COLOUR_YELLOW 0xFFFF00AA
#define COLOUR_WHITE 0xFFFFFFAA
#define COLOUR_BLUE 0x0000BBAA
#define COLOUR_LIGHTBLUE 0x33CCFFAA
#define COLOUR_ORANGE 0xFF9900AA
#define COLOUR_RED 0xAA3333AA
#define COLOUR_LIME 0x10F441AA
#define COLOUR_MAGENTA 0xFF00FFFF
#define COLOUR_NAVY 0x000080AA
#define COLOUR_AQUA 0xF0F8FFAA
#define COLOUR_CRIMSON 0xDC143CAA
#define COLOUR_FLBLUE 0x6495EDAA
#define COLOUR_BISQUE 0xFFE4C4AA
#define COLOUR_BLACK 0x000000AA
#define COLOUR_CHARTREUSE 0x7FFF00AA
#define COLOUR_BROWN 0XA52A2AAA
#define COLOUR_CORAL 0xFF7F50AA
#define COLOUR_GOLD 0xB8860BAA
#define COLOUR_GREENYELLOW 0xADFF2FAA
#define COLOUR_INDIGO 0x4B00B0AA
#define COLOUR_IVORY 0xFFFF82AA
#define COLOUR_LAWNGREEN 0x7CFC00AA
#define COLOUR_SEAGREEN 0x20B2AAAA
#define COLOUR_LIMEGREEN 0x32CD32AA 
#define COLOUR_MIDNIGHTBLUE 0X191970AA
#define COLOUR_MAROON 0x800000AA
#define COLOUR_OLIVE 0x808000AA
#define COLOUR_ORANGERED 0xFF4500AA
#define COLOUR_PINK 0xFFC0CBAA 
#define COLOUR_SEAGREEN 0x2E8B57AA
#define COLOUR_SPRINGGREEN 0x00FF7FAA
#define COLOUR_TOMATO 0xFF6347AA 
#define COLOUR_YELLOWGREEN 0x9ACD32AA 
#define COLOUR_MEDIUMAQUA 0x83BFBFAA
#define COLOUR_MEDIUMMAGENTA 0x8B008BAA 
/*---------*/

/* Colours - Embedded */
#define EMBED_COLOUR_GREY "AFAFAF"
#define EMBED_COLOUR_GREEN "33AA33"
#define EMBED_COLOUR_RED "AA3333"
#define EMBED_COLOUR_YELLOW "FFFF00"
#define EMBED_COLOUR_WHITE "FFFFFF"
#define EMBED_COLOUR_BLUE "0000BB"
#define EMBED_COLOUR_LIGHTBLUE "33CCFF"
#define EMBED_COLOUR_ORANGE "FF9900"
#define EMBED_COLOUR_RED "AA3333"
#define EMBED_COLOUR_LIME "10F441"
#define EMBED_COLOUR_MAGENTA "FF00FF"
#define EMBED_COLOUR_NAVY "000080"
#define EMBED_COLOUR_AQUA "F0F8FF"
#define EMBED_COLOUR_CRIMSON "DC143C"
#define EMBED_COLOUR_FLBLUE "6495ED"
#define EMBED_COLOUR_BISQUE "FFE4C4"
#define EMBED_COLOUR_BLACK "000000"
#define EMBED_COLOUR_CHARTREUSE "7FFF00"
#define EMBED_COLOUR_BROWN "A52A2A"
#define EMBED_COLOUR_CORAL "FF7F50"
#define EMBED_COLOUR_GOLD "B8860B"
#define EMBED_COLOUR_GREENYELLOW "ADFF2F"
#define EMBED_COLOUR_INDIGO "4B00B0"
#define EMBED_COLOUR_IVORY "FFFF82"
#define EMBED_COLOUR_LAWNGREEN "7CFC00"
#define EMBED_COLOUR_SEAGREEN "20B2AA"
#define EMBED_COLOUR_LIMEGREEN "32CD32" 
#define EMBED_COLOUR_MIDNIGHTBLUE "191970"
#define EMBED_COLOUR_MAROON "800000"
#define EMBED_COLOUR_OLIVE "808000"
#define EMBED_COLOUR_ORANGERED "FF4500"
#define EMBED_COLOUR_PINK "FFC0CB" 
#define EMBED_COLOUR_SEAGREEN "2E8B57"
#define EMBED_COLOUR_SPRINGGREEN "00FF7F"
#define EMBED_COLOUR_TOMATO "FF6347" 
#define EMBED_COLOUR_YELLOWGREEN "9ACD32" 
#define EMBED_COLOUR_MEDIUMAQUA "83BFBF"
#define EMBED_COLOUR_MEDIUMMAGENTA "8B008B" 
/*--------------------*/

/* Maximum Values */

/*----------------*/